title: Just the Docs PatJas
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://patjas93.github.io/JTD

aux_links:
  Template Repository: https://github.com/patjas93/JTD
